# Generated by Django 3.2.7 on 2021-09-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fb_url',
            field=models.URLField(blank=True, default='', verbose_name='facebook url'),
        ),
    ]
