# Generated by Django 3.2.7 on 2021-09-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('is_public', models.BooleanField(default=True, verbose_name='public')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_set', to='main.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main.models.term_image_upload_to)),
                ('term', models.TextField()),
                ('definition', models.TextField()),
                ('term_lang', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='en', max_length=10)),
                ('definition_lang', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese')], default='vi', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='main.set')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='sets',
            field=models.ManyToManyField(blank=True, to='main.Set'),
        ),
    ]
