# Generated by Django 3.2.7 on 2021-09-24 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210923_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='set_folder', to='main.Set'),
        ),
        migrations.AlterField(
            model_name='set',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set', to=settings.AUTH_USER_MODEL),
        ),
    ]
