# Generated by Django 3.2.7 on 2021-09-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210925_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdetail',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_detail', to='main.set'),
        ),
    ]
