# Generated by Django 3.2.7 on 2021-10-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_setdetail_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setdetail',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
