# Generated by Django 3.2.7 on 2021-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211008_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='sets',
            field=models.ManyToManyField(blank=True, related_name='set_folders', related_query_name='set_folder', to='main.Set'),
        ),
    ]
