# Generated by Django 3.2.7 on 2021-11-06 06:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_folder_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.set_image_upload_to),
        ),
    ]
