# Generated by Django 3.2.9 on 2021-11-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_set_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
    ]
